---
- hosts: localhost
  vars:
    openshift_namespace: amq-stage
    openshift_service_account: amq-service-account

  tasks:
    - name: Create OpenShift namespace
      k8s:
        name: "{{ openshift_namespace }}"
        api_version: v1
        kind: namespace
        state: present

    - name: Create OpenShift service account
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: "{{ openshift_service_account }}"
            namespace: "{{ openshift_namespace }}"

    - name: Add OpenShift view role to service account
      k8s:
        state: present
        definition:
          apiVersion: authorization.openshift.io/v1
          kind: RoleBinding
          groupNames: null
          metadata:
            name: view
            namespace: "{{ openshift_namespace }}"
          roleRef:
            name: view
          subjects:
            - kind: ServiceAccount
              name: "{{ openshift_service_account }}"
              namespace: "{{ openshift_namespace }}"
          userNames:
            - "system:serviceaccount:{{ openshift_namespace }}:{{ openshift_service_account }}"

    - name: Check if already deployed
      command:
        oc get dc broker-amq
      register: amq_dc
      ignore_errors: yes
      failed_when: False
      no_log: True

    - name: Generate certificates and keystore and deploy
      block: 
        - name: Create temporary directory to hold generated certificates and keystore
          tempfile:
            state: directory
          register: cert_dir

        - name: Generate certificate private key
          openssl_privatekey:
            path: "{{ cert_dir.path }}/key.pem"

        - name: Generate certificate sign request
          openssl_csr:
            path: "{{ cert_dir.path }}/csr.pem"
            privatekey_path: "{{ cert_dir.path }}/key.pem"
            common_name: broker-amq
            country_name: US
            state_or_province_name: CA
            locality_name: San Diego
            organization_name: Sempra Energy
            organizational_unit_name: IT

        - name: Generate certificate for key store
          openssl_certificate:
            path: "{{ cert_dir.path }}/certificate.pem"
            privatekey_path: "{{ cert_dir.path }}/key.pem"
            csr_path: "{{ cert_dir.path }}/csr.pem"
            provider: selfsigned

        - name: Generate keystore password
          set_fact:
            keystore_password: "{{ lookup('password', '/dev/null length=15') }}"

        - name: Create PKCS#12
          openssl_pkcs12:
            action: export
            path: "{{ cert_dir.path }}/chain.p12"
            friendly_name: broker
            certificate_path: "{{ cert_dir.path }}/certificate.pem"
            privatekey_path: "{{ cert_dir.path }}/key.pem"
            passphrase: "{{ keystore_password }}"
            state: present

        - name: Show generated password ---- TODO REMOVE THIS WHEN FINISHED
          debug:
            var: keystore_password

        - name: Import PKCS#12 into key store
          java_cert:
            pkcs12_path: "{{ cert_dir.path }}/chain.p12"
            pkcs12_password: "{{ keystore_password }}"
            pkcs12_alias: broker
            cert_alias: broker
            keystore_path: "{{ cert_dir.path }}/keystore"
            keystore_pass: "{{ keystore_password }}"
            keystore_create: yes
            state: present

        - name: Generate OpenShift secrets from key store
          debug: msg="TODO"

        - name: Deploy
          shell: >
            oc process openshift//amq63-basic -o yaml | oc create -f -

        - name: Remove temporary directory housing generated certificates and keystore
          file:
            state: absent
            path: "{{ cert_dir.path }}"
          when: False
      when: amq_dc.rc != 0

    - name: Retrieve deployment configuration
      command: >
        oc get dc broker-amq -o yaml
      register: amq_dc

    - name: Update deployment configuration to include service account
      k8s:
        state: present
        definition:
          apiVersion: apps.openshift.io/v1
          kind: DeploymentConfig
          metadata:
            name: broker-amq
            namespace: "{{ openshift_namespace }}"
          spec:
            template:
              metadata:
                name: broker-amq
              spec:
                serviceAccount: "{{ openshift_service_account }}"
                serviceAccountName: "{{ openshift_service_account }}"

    - name: Add secrets to OpenShift service account
      debug: msg="TOOD"

    - name: Expose route
      debug: msg="TODO"
